// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:ensom/local/offline_queue_entry.dart';
import 'package:ensom/local/place_cache_entry.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(OfflineQueueEntryAdapter());
    registerAdapter(PlaceCacheEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(OfflineQueueEntryAdapter());
    registerAdapter(PlaceCacheEntryAdapter());
  }
}
